### PR TITLE
New Door Sounds!

### PR DESCRIPTION
**Pull request by OctusGit**
## About The Pull Request

Adds new door sound effects ported over from that one cursed codebase that shall not be named.

- https://github.com/quotefox/Hyper-Station-13/pull/1054

## Why It's Good For The Game

More high-quality door noises that give better information, as well as just sounding a lot more *crisp* really are things that add up to immersion. Plus they're rather unique.

**Blast Door Close**
https://vocaroo.com/177H7OLBzgQ8
**Blast Door Open**
https://vocaroo.com/1cOqfsA2nu90
**Bolts Down**
https://vocaroo.com/1ormqks7dKoZ
**Bolts Up**
https://vocaroo.com/1nfZaoxlL8r4
**Windoor**
https://vocaroo.com/1a8QI98JhQ1R
**Shutters** (Waiting on Demodulerization as it conflicts, will add after)
https://vocaroo.com/1eF6IyokXSFi
## Changelog

:cl: CapnMachaddish
soundadd: windowdoor.ogg
soundadd: blastDoorOpen.ogg and blastDoorClose.ogg
soundadd: shutter.ogg
soundadd: boltsDown.ogg and boltsUp.ogg
del:Deleted old module sounds from aesthetics folder
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
Changelogs:

Don't currently work anyways, I'm fixing that in #783 
DO NOT SUPPORT MARKDOWN AT ALL.

**Comment by SabreML** [comment]
This and #730 will definitely conflict with each other, specifically with the blastdoor and shutter sounds.

**Review by ElorgRHG — COMMENTED** [review]
Personal opinion, take that as you will

I dont like the windoor sound, its too... sharp?
The bolting sounds also seem a bit too _futuristic_ for SS13 but that's whatever.

**Comment by Kapu1178** [comment]
🔑 no likey

**Pull request closed without merging**
