### PR TITLE
Adds Wrestling and more

### PR DESCRIPTION
**Pull request by Tokorizo**
## About The Pull Request

ORIGINAL PR: https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285
Ports **some** features from this PR, mostly the ability to suplex people, head slam them down to the floor and bend their arms and legs to break and dislocate.

## Why It's Good For The Game

Having more options to combat and fleshing it out is useful for adding options to how you approach fights. It also acts as a useful tool in RP situations or to disable someone without beating them to death.

## Changelog

:cl:Azarak
add: Wrestling moves
/:cl:

### CODE REVIEW

**Review by Kapu1178 — CHANGES_REQUESTED** [review]
Code quality is kinda shit, and why is this all in a defines file?

**Comment by Tokorizo** [comment]
> Code quality is kinda shit, and why is this all in a defines file?

Your gonna have to actually review the code instead of just saying it's bad if we want to improve it. Also, I can just fix the defines thing by moving it to the appropriate place.

**Comment by Kapu1178** [comment]
I don't even know where to start. It's all in an if, theres switches that should just be `if` statements, it utilizes the dot in the most abstract and unnecessary way either.

**Comment by Tokorizo** [comment]
Yeah, we can prob do this later. Too big for me to fix it.

**Pull request closed without merging**
