### PR TITLE
Fixes our URL Buttons

### PR DESCRIPTION
**Pull request by Tokorizo**
## About The Pull Request

Changes the URL's for the UI buttons to go to our stuff, wiki, discord, github.

## Why It's Good For The Game

Were not TG, giving people wrong information like incorrect space-law is bad for establishing our differences. 

## Changelog

:cl:
config: changed the ingame panel URL's to our sources
/:cl:

### CODE REVIEW

**Review by ElorgRHG — COMMENTED** [review]
I'd like to inform you that what you've modified will _most likely_ get overriden by the actual config in `config\config.txt`, thus, making this PR not do anything really

**Comment by SabreML** [comment]
> I'd like to inform you that what you've modified will _most likely_ get overriden by the actual config in `config\config.txt`, thus, making this PR not do anything really

Probably still worth changing the defaults though, if only so that the repo's config files are up to date with the server's.

**Comment by Tokorizo** [comment]
> config\config.txt

I can simply edit that in TGS, not an issue. Like Sabre said,

> Probably still worth changing the defaults though, if only so that the repo's config files are up to date with the server's.

This still will need to be done just to continue.

**Comment by Tokorizo** [comment]
I'm updating the TGS so I won't be making the edit here.

**Review by ElorgRHG — APPROVED** [review]
Guess there's nothing wrong here

**Pull request merged**
