### PR TITLE
Revert "[SEMI MODULAR] Ports the IC Spawning Module from SR"

### PR DESCRIPTION
**Pull request by francinum**
Reverts pariahstation/Pariah-Station#517

There's something wrong about this PR that results in the `Spawn` adminverb allowing a mob as a valid argument. This is mostly a stopgap.

### CODE REVIEW

**Comment by francinum** [comment]
https://www.byond.com/forum/post/2786615

**Comment by Kapu1178** [comment]
dnm deez nuts

**Comment by francinum** [comment]
> dnm deez nuts

When

**Comment by SabreML** [comment]
> When

When You Code It

**Review by SabreML — APPROVED** [review]

**Pull request merged**
