### PR TITLE
Gamuioda (Moth) head shape update: They actually look like bugs now, woah.

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request
I'll probably get my shins eaten for this.

What it says on the tin, changes the shape of Moth heads to look more insectlike. Makes our species slightly more unique from the others.
Changes:
image
image
image

What it looks like currently.
image

## Why It's Good For The Game
Unique species looks :]

## Changelog

:cl:
imageadd: Moths now have a slightly altered head and eye shape.
/:cl:

### CODE REVIEW

**Comment by SabreML** [comment]
Closing and re-opening because the diffbots missed this.

**Comment by SabreML** [comment]
Would it be worth adding 'missing' sprites as well for the new eyes? The old ones didn't have any either, but it's a bit more obvious now:
**Old:**
Before
**New:**
After

**Comment by Ebin-Halcyon** [comment]
> Would it be worth adding 'missing' sprites as well for the new eyes? The old ones didn't have any either, but it's a bit more obvious now since they're bigger: **Old:** Before **New:** After


Yeh, I can add the sprites, I just have no clue how to code them in, lol.

**Comment by SabreML** [comment]
> Yeh, I can add the sprites, I just have no clue how to code them in, lol.

With the way it's currently set up, you just need to set the `species_eye_path` variable on `/datum/species/moth` to a new dmi file containing the 'eyes' and 'eyes_missing' icon states.
For example the way it's working for Skrell:
https://github.com/pariahstation/Pariah-Station/blob/4749a62e1b27913138e227a3cc7b7592057f6f66/code/modules/mob/living/carbon/human/species_types/skrell.dm#L17
image

**Comment by Ebin-Halcyon** [comment]
> > Yeh, I can add the sprites, I just have no clue how to code them in, lol.
> 
> With the way it's currently set up, you just need to set the `species_eye_path` variable on `/datum/species/moth` to a new dmi file containing the 'eyes' and 'eyes_missing' icon states. For example the way it's working for Skrell:
> 
> https://github.com/pariahstation/Pariah-Station/blob/4749a62e1b27913138e227a3cc7b7592057f6f66/code/modules/mob/living/carbon/human/species_types/skrell.dm#L17
> 
> 
> image

Gotcha, i'll get to it shortly.

**Comment by Ebin-Halcyon** [comment]
They now have eyes and removed eye sprites.

image
image

**Pull request merged**
