### PR TITLE
[MDB IGNORE] Ports ZAS from Baystation

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request
Warcrimes

## Why It's Good For The Game
Funny atmos go brrrr

## Changelog

:cl:
/:cl:

### CODE REVIEW

**Comment by Ebin-Halcyon** [comment]
:pray:

**Comment by Troontjelolo** [comment]
>Actually trying to port ZAS
https://youtu.be/DmvSieBFPNM?t=12

god speed madman

**Comment by Tokorizo** [comment]
This entire PR
https://www.youtube.com/watch?v=DNeikvoqQ-s

**Comment by Kapu1178** [comment]
> This entire PR https://www.youtube.com/watch?v=DNeikvoqQ-s

IT WORKED FOR KAPULIMBS IT WILL WORK FOR ZAS

**Comment by E-MonaRhg** [comment]
o no
_can you review this yourself, I dont want to_

**Comment by Kapu1178** [comment]
Redoing this on a fresh branch with less autism and better understanding

**Pull request closed without merging**
