### PR TITLE
Removes ERP Pref from the code

### PR DESCRIPTION
**Pull request by Tokorizo**
## About The Pull Request

BYE BYE ERP MWHAHAHAHA

## Why It's Good For The Game

ERP is bad

## Changelog

:cl:
del: Removed ERP pref code from TGUI, since we no longer have ERP
/:cl:

### CODE REVIEW

**Comment by SabreML** [comment]
a sad day for the server

**Comment by michaelyesok** [comment]
1984

**Review by francinum — APPROVED** [review]

**Comment by Tokorizo** [comment]
Guys please. People are gonna think your serious 😂

**Comment by ElorgRHG** [comment]
This is so sad

Octus, delete subtler

**Pull request merged**
