### PR TITLE
Oracle UI

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request
Ports OracleUI from... Oracle. It's a lightweight, extremely simple html wrapper that looks pretty and is extremely easy to use. It even has a development tool that doesn't require booting the game.

Contributor guidelines will be updated to make clear that UIs that already use TGUI are not to be made with Oracle UI. You need an extremely good reason to change something's UI standard. Disposals was done as a testcase and to provide a groundwork for new contributors to make their first UIs.

* https://github.com/OracleStation/OracleStation/pull/702
* https://github.com/OracleStation/OracleStation/pull/788

Along with some tweaks by me.

## Why It's Good For The Game
Having a simple UI standard for our small contributor base is important. TGUI is kind of a nightmare for people who haven't worked with any programming language before, let alone webshit garbage.

## Changelog
:cl:
add: Oracle UI
refactor: Disposals now uses Oracle UI
/:cl:

### CODE REVIEW

**Comment by Sinestia** [comment]
If someone can't figure out tgui then I don't really expect them to get this either

both are pretty simple when it comes to making basic UIs like disposals

not that oracle ui isnt cool tho

**Comment by Zonespace27** [comment]
👎 Personal opinion but I prefer coding for and looking at tgui over this

**Comment by SabreML** [comment]
Putting this here as well so that it's actually on the PR and won't just get lost forever on Discord:
<hr>

image
([Message link](https://discord.com/channels/957063236635734026/957076739744485397/982405436340850718))
<details>
<summary>Text:</summary>
<blockquote>

1: It's adding a whole separate UI system in a completely different coding language with completely different standards and guidelines to probably 80%+ of the existing interfaces.

2: It's really not *that* much simpler than the Javascript equivalent. The disposals UI for example went from 45 lines (if you're only counting the UI code) to 27 lines. It's faster to write, sure, but it's probably around the same level of complexity as long as you understand the basics of both languages.

2.5: Same sort of thing with the IDE; It's definitely useful to have, and if you're making the UI before implementing the code then it's an improvement over the debug server, but if you've added `ui_interact()` to the DM side then they're both around equal. Arguably the TGUI dev server is slightly better since it can tell you exactly what's being sent to the UI.

3: Personally, I think it looks worse than TGUI does, but that's a pretty weak point because it's subjective and all in CSS anyway.

4: I can't think of another separate issue but you get the idea.

My main concern really is that I don't like the idea of having two conflicting standards when the existing one seems to work perfectly fine already.
If you're just using TGUI to make UIs and not... whatever the preferences interface is, then personally at least I find it incredibly easy to write code for. Moreso than DM even.
</blockquote>
</details>

<hr>

image
([Message link](https://discord.com/channels/957063236635734026/957076739744485397/982460057545494618))
<details>
<summary>Text:</summary>
<blockquote>

am home

1\. It's not a completely different language. It's <i>INCREDIBLY</i> simple HTML with CSS for theming. HTML can hardly be considered a programming language. 

2\. It is really that much simpler. The UI itself is simple HTML, which is as simple as a user interface can get. The DM-UI interfacing with OracleUI is roughly the same as TGUI as far as I can tell, though OUI has its own suite of procs that it bounces through like `oui_can_view()`

2.5: OracleUI has the `oui_data_debug()` proc (which i made into a context menu verb as well) that dumps the json output of what the client currently sees.

3\. I think it looks better, but yeah, CSS be like.

I think OracleUI is worthwhile, especially because its so self-contained, unlike TGUI. Oracle UIs are <b><i>entirely</i></b> self contained, besides from the parent atom having a reference to them.
</blockquote>
</details>
<hr>
(I'll reply to the reply soon-ish when I'm actually able to write something.)

**Comment by Tokorizo** [comment]
Yeah I'm not personally a fan of having a new UI system when TGUI exist. I've seen multiple people saying that its better to learn TGUI than port an entirely different UI system for reasons I can agree with. I'm for the opinion that people should just learn TGUI, to avoid inconsistency with UIs in the future. And because noobs to UI (like myself) would appreciate more to learn the difficult than to use the easier alternative.

**Pull request closed without merging**
