### PR TITLE
EMOTES (DONE)

### PR DESCRIPTION
**Pull request by Tokorizo**
## About The Pull Request
Adds audible and more emotes from the game, ported from multiple codebases.

## Why It's Good For The Game
Expression good

## Changelog

:cl:
add: Adds emotes to the game
code: Raises the minimum character age from 17 to 18
/:cl:

### CODE REVIEW

**Review by E-MonaRhg — CHANGES_REQUESTED** [review]
These **really** need species restrictions, I dont want to see humans (or other) growling, hissing and other stuff, won't be approving this until they get restricted.
Also, please remove commented stuff too, I dont know why you kept these.

And as this is a sound PR, I have some reviews regarding these aswell:
Unused sounds:
`annoyed.ogg`
`blush.ogg`
`cat_scream.ogg`
`dwoop.ogg`
`jelly_scream.ogg`
`mothlaugh.ogg`
`Nose_boop.ogg`
`nyaha.ogg`, `nyaha1.ogg`, `nyaha2.ogg`
`nyehehe.ogg`
`question.ogg`
`raptorscream.ogg`
`realize.ogg`
`rodentscream.ogg`
`scream_moth.ogg` - duplicate
`sweatdrop.ogg`
`synth_no.ogg`
`synth_yes.ogg`

`voxcough.ogg`
`voxrustle.ogg`
`voxscream.ogg`
`voxsneeze.ogg`

`yawn_m1.ogg`, `yawn_m2.ogg`
`zombie_scream.ogg`
`female_cough1.ogg`, `female_cough2.ogg`, `female_cough3.ogg`
`female_giggle_1.ogg`, `female_giggle_2.ogg`
`female_sneeze.ogg`

`male_cough1.ogg`, `male_cough2.ogg`, `male_cough3.ogg`
`male_sneeze.ogg`
`male_sniff.ogg`

Other:
`claponce1.ogg` sounds terrible
`woof.ogg` I know we're planning on adding something vulp-ish, but I dont want them actually going around and basically barking at people
`meow.ogg` I dont like the sound, and a similar comment as the above too

On emotes that check `if(user.gender == MALE)`, it returns female sounds for the *other* gender/genderless too

**Comment by Tokorizo** [comment]
We don't have species yet that the sounds are going to be restricted to in order to actually well, restrict them. We will have to do this later when we do finish our work after Klimbs is downstream, for now, id like these to be put in because they're pretty nice to the code, and a lot of people are familiar with it. Concerns are valid about letting humans hiss and growl, but this is just the base work so we can fix it later down the line. When we actually get out species.

**Review by E-MonaRhg — APPROVED** [review]
I'll handle the emote restrictions myself

**Comment by LemonInTheDark** [comment]
If you're gonna port stuff from other codebases, you should really be crediting the people who's work you're using

**Pull request merged**
