### PR TITLE
[WIP] Teshari

### PR DESCRIPTION
**Pull request by SabreML**
## About The Pull Request
Adds Teshari as a species.

A lot of the bulk of this PR is just from setting `supports_variation_flags` on clothing, so I've tried to split up the commits as much as I can in order to help with reviews.

From what I've tested so far, everything *seems* to be working properly. There's bound to be some things I've missed of course, but in theory this should be all that's left to do:
- [x] Greyscale clothing.
- [x] Lore-accurate species modifiers ~~and features.~~
- [x] Species description text.
- [ ] Species lore text.
- [x] Extra customisation features.
- [x] Screenshots for the PR description.
- [ ] #729
- [x] More thorough testing.

(A lot of code was referenced from #218, #480, Skyrat's Teshari, and Shiptest's Kepori, so thanks to them.)

## Teshari Images
For all of these screenshots, I used these colour settings in order to make each body section easier to differentiate:
| Setting | Colour |
| -------- | ------- |
| **Mutant Colour:** | `#FF0000` |
| **Secondary Mutant Colour:** | `#FF00FF` |
| **Tertiary Mutant Colour:** | `#00FFFF` |
| **Eye Colour:** | `#FFFF00` |
| **Head Feathers:** | `#00FF00` |
| **Body Feathers:** | `#0000FF` |

<details>
<summary><b>Directional Sprites:</b></summary>

**South:**
South
**North:**
North
**East:**
East
**West:**
West
</details>

<details>
<summary><b>Customisation Options:</b></summary>

**Species Description:**
Species Description
**Main Features:**
Secondary Features
**Colours:**
Colours
**Head Feathers:**
Feathers
**Body Feathers:**
Body Feathers
**Ears:**
Ears
**Tails:**
Tails
</details>

<details>
<summary><b>Job Outfits:</b></summary>

**Assistant:**
Assistant
**Atmospheric Technician:**
Atmospheric Technician
**Bartender:**
Bartender
**Botanist:**
Botanist
**Captain:**
Captain
**Cargo Technician:**
Cargo Technician
**Chaplain:**
Chaplain
**Chemist:**
Chemist
**Chief Engineer:**
Chief Engineer
**Chief Medical Officer:**
Chief Medical Officer
**Clown:**
Clown
**Cook:**
Cook
**Curator:**
Curator
**Detective:**
Detective
**Geneticist:**
Geneticist
**Head of Personnel:**
Head of Personnel
**Head of Security:**
Head of Security
**Janitor:**
Janitor
**Lawyer:**
Lawyer
**Medical Doctor:**
Medical Doctor
**Mime:**
Mime
**Paramedic:**
Paramedic
**Prisoner:**
Prisoner
**Psychologist:**
Psychologist
**Quartermaster:**
Quartermaster
**Research Director:**
Research Director
**Roboticist:**
Roboticist
**Scientist:**
Scientist
**Security Officer:**
Security Officer
**Shaft Miner:**
Shaft Miner
**Shaft Miner (Equipment):**
Shaft Miner (Equipment)
**Station Engineer:**
Station Engineer
**Virologist:**
Virologist
**Warden:**
Warden
</details>

## Why It's Good For The Game
🐦

## Changelog

:cl:
add: Teshari!
/:cl:

### CODE REVIEW

**Comment by Ebin-Halcyon** [comment]
Yo, gonna point out some items that aren't used here or are missing directionals:

Missing directionals:
`militarywebbing` - Belt.dmi

Unused
`ranger cloak and trims` - Neck.dmi
`syndievest_winter` - Suit.dmi

**Comment by SabreML** [comment]
Oh, thanks! I completely missed those.

**Comment by SabreML** [comment]
Just as an update, I'll be gone until Monday so I won't have a chance to work on this until then.
It shouldn't take too long after that to get greyscale clothing to work though.

**Comment by SabreML** [comment]
Other than lore stuff, this *should* now be feature-complete.

**Comment by SabreML** [comment]
> Other than lore stuff, this *should* now be feature-complete.

It turns out that Citadel has a whole bunch of Teshari customisation options, so I'll try to port some of those over as well.

**Comment by SabreML** [comment]
(Small rebase to clean up some commits)

**Review by Ebin-Halcyon — COMMENTED** [review]
I personally didn't use alot of the Cit/Virgo sprites cause alot of them are awkwardly out of proportion or low quality. They're fine for now but i'll probably replace it down the line.

**Comment by SabreML** [comment]
> I personally didn't use alot of the Cit/Virgo sprites cause alot of them are awkwardly out of proportion or low quality. They're fine for now but i'll probably replace it down the line.

Yeah, I skipped a bunch of them which were either just the human sprite slightly offset or which didn't work very well with the existing sprites. Inevitably though some of them will have snuck in anyway.

**Comment by Ebin-Halcyon** [comment]
> > I personally didn't use alot of the Cit/Virgo sprites cause alot of them are awkwardly out of proportion or low quality. They're fine for now but i'll probably replace it down the line.
> 
> Yeah, I skipped a bunch of them which were either just the human sprite slightly offset or which didn't work very well with the existing sprites. Inevitably though some of them will have snuck in anyway.

👌

**Review by Tokorizo — APPROVED** [review]

**Pull request merged**
