### PR TITLE
`tgstation.dme` -> `pariah.dme`

### PR DESCRIPTION
**Pull request by SabreML**
## About The Pull Request
**DNM unless you're Francinum.**

Changes `tgstation.dme` to `pariah.dme`, as well as everything referencing it.

## Why It's Good For The Game
We hardforked almost a month ago, so now we're actually able to set ourselves apart from the long list of TG downstreams.

For example in StrongDMM:
**Before:**
*(Try to guess which one is Pariah)*
image

**After:**
image

## Changelog

:cl:
server: Changed tgstation.dme (and associated files) to pariah.dme
/:cl:

### CODE REVIEW

**Comment by SabreML** [comment]
The icebox failure is being caused by an unrelated lighting runtime: (Seems to be a TG issue, based on https://github.com/tgstation/tgstation/pull/67201)
image

No idea what the cause is but I'll try looking into it.

**Comment by SabreML** [comment]
*Another* unrelated runtime, this time a lot easier to debug:
image

**Comment by SabreML** [comment]
shoo

**Review by francinum — APPROVED** [review]
LGTM

**Pull request merged**
