### PR TITLE
Ports screen alerts from TGMC

### PR DESCRIPTION
**Pull request by Kapu1178**
ports:

- https://github.com/tgstation/TerraGov-Marine-Corps/pull/8576

## About The Pull Request
title

## Why It's Good For The Game
its cool

## Changelog
:cl: Kapu1178, Tiviplus
code: TGMC screen alerts.
/:cl:

### CODE REVIEW

**Review by Tokorizo — APPROVED** [review]
This is pretty neat, no arguments here.

**Comment by LYNXEMS** [comment]
How about at least a verb for admins to just slap it for a single person or everyone?

**Comment by Kapu1178** [comment]
> How about at least a verb for admins to just slap it for a single person or everyone?

Im not bloating the admin verb list. Learn to use SDQL if you need to do advanced bus.

`CALL play_screen_text("") ON /mob IN global.player_list WHERE client NOT NULL`
`CALL play_screen_text("") ON /mob IN global.player_list WHERE ckey == "Kapu1178"`

**Comment by ElorgRHG** [comment]
I fail to find a reason for this PR, made for TGMC originally because players there are too focused on shooting gun to look at their chatbox to see the announcements.

On shiptest it displays the *planet details*, so the name of the planet and local hour which doesnt change between planets, and the last words of someone who died, which looks REALLY out of place, and, opinion time, kinda crap.

So all and all, their use here, beside the rare case of admin abuse, would be...?

**Comment by Kapu1178** [comment]
> I fail to find a reason for this PR, made for TGMC originally because players there are too focused on shooting gun to look at their chatbox to see the announcements.
> 
> On shiptest it displays the _planet details_, so the name of the planet and local hour which doesnt change between planets, and the last words of someone who died, which looks REALLY out of place, and, opinion time, kinda crap.
> 
> So all and all, their use here, beside the rare case of admin abuse, would be...?

Im gonna add it to some stuff to do with ZAS.

**Comment by LYNXEMS** [comment]
> > How about at least a verb for admins to just slap it for a single person or everyone?
> 
> Im not bloating the admin verb list. Learn to use SDQL if you need to do advanced bus.
> 
> `CALL play_screen_text("") ON /mob IN global.player_list WHERE client NOT NULL` `CALL play_screen_text("") ON /mob IN global.player_list WHERE ckey == "Kapu1178"`

Just used to SDQL being disabled, but I know of its use. If not verbs, then even something like player panel would be bad for it as a different message type somewhere?

**Comment by ElorgRHG** [comment]
>Im gonna add it to some stuff to do with ZAS.

That's more *purposeful* I suppose, but *what* stuff with ZAS though

**Comment by Kapu1178** [comment]
> > Im gonna add it to some stuff to do with ZAS.
> 
> That's more _purposeful_ I suppose, but _what_ stuff with ZAS though

debugging tools primarily. This change is completely "modular" and can always just be removed if unused.

**Pull request merged**
