### PR TITLE
A small amount of cargo drip and resprites

### PR DESCRIPTION
**Pull request by ElorgRHG**
## About The Pull Request
Ports: https://github.com/Skyrat-SS13/Skyrat-tg/pull/14110, https://github.com/tgstation/tgstation/pull/66570, and a bit of https://github.com/Skyrat-SS13/Skyrat-tg/pull/13194

Resprites cargo clothing, adds cargo turtlenecks and skirtlenecks - cargo tech version and QM version
Adds a garment bag to the QM's locker to lessen the clutter a bit.

VERY LARGE IMAGES OF THE SPRITES IN THE DETAILS
**(trigger warning, codersprites, including codersprites for vox and teshari, you have been warned)**

QM clothing:
<details>

image

image

image

image

</details>

Cargo tech clothing:
<details>

image

image

image

image

</details>

Miner clothing that's not actually used by miners
<details>

image

</details>

## Why It's Good For The Game
I like cargo. (and these sprites)

## Changelog

:cl:Ebin-Halcyon, Spc-Dragonfruits, PositiveEntropy, ElorgRHG
add: Added some new cargo clothes, and resprited the old ones.
add: Added a garment bag for the quartermaster with all of their clothes and put it in their locker.
qol: Quartermaster's wintercoat can now hold their telescopic baton in its suit store slot.
/:cl:
_Big thanks to Hal for the digi sprites and the help with making the teshari sprites look less shit_ ❤️

### CODE REVIEW

**Review by Ebin-Halcyon — COMMENTED** [review]
Wait a minute, did you mean to add all that stuff to the digi file? Or is that IDB fucking up.

**Comment by ElorgRHG** [comment]
> Wait a minute, did you mean to add all that stuff to the digi file? Or is that IDB fucking up.

I moved the file from modular files and changed its name, its most likely counting it as a new file now so I technically _did_ add all of that, not an issue though

**Comment by francinum** [comment]
The mining outfits look perfectly fine.

I'm trying to find a less harsh way to say that the others kinda look like they are made entirely of 80% reflective matte-finish plastic.

**Comment by Ebin-Halcyon** [comment]
> The mining outfits look perfectly fine.
> 
> I'm trying to find a less harsh way to say that the others kinda look like they are made entirely of 80% reflective matte-finish plastic.

Coders fear the good color palette.

**Pull request closed without merging**
