### PR TITLE
fast food

### PR DESCRIPTION
**Pull request by PhoenixAM**
## About The Pull Request

food no longer takes an eternity to make

## Why It's Good For The Game

QOL

## Changelog

:cl:
qol: makes food craft faster
/:cl:

### CODE REVIEW

**Comment by E-MonaRhg** [comment]
Add a comment saying you changed something since its not modular, `//PARIAH EDIT` will do

**Review by E-MonaRhg — CHANGES_REQUESTED** [review]
Oh yeah I can request changes _properly_, see above comment

**Comment by PhoenixAM** [comment]
Accidentally did that, whoops! Got it.

**Review by Tokorizo — APPROVED** [review]
Looks good, no real complaint here but its a nice first PR. Hope to see more contributions.

**Review by E-MonaRhg — APPROVED** [review]
Changed the `config:` to `qol:` in the CL not to bog this PR down with requesting that change, hope you dont mind.

Otherwise, good first PR, welcome to Pariah!

**Pull request merged**
